spring:
  application:
    name: mood-related-weather
  datasource:
    url: jdbc:postgresql://db:5432/mood_weather
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

openweather:
  api:
    key: be32f368ea9a2bc5fed337439e80163d

jwt:
  secret: supersecretkeysupersecretkeysupersecretkey
  expiration: 3600000

server:
  port: 8080