spring:
  application:
    name: mood-related-weather
  datasource:
    url: jdbc:postgresql://localhost:5432/mood_weather
    username: postgres
    password: AromanouskiJ2007

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

openweather:
  api:
    key: be32f368ea9a2bc5fed337439e80163d

server:
  port: 8080